#!/bin/sh
printf '\033[7;1H'            # goto line 7
printf '\033[1m\033[35m'      # bold and magenta
figlet -t -c -f script End
printf '\033[0m'              # reset font
printf '\033[18;14H'          # goto line 18
printf 'Please reach out if you have questions or feature requests.\n'
